#!/usr/bin/env bash
set -euo pipefail

# ==========================================
#  pirate-litewalletjni cross toolchain setup
#  Ubuntu 24.04+ (noble and newer)
#  - Linux x86_64 (native)
#  - Linux aarch64 (cross)
#  - Windows x86_64 (GNU / mingw-w64)
#
#  Notes:
#   - macOS dylib cross-compile is not included (needs Apple SDK/osxcross).
#   - This script installs system toolchains and rust targets.
#   - It also writes a .cargo/config.toml in the current directory (repo root)
#     unless you disable that section.
# ==========================================

log()  { echo -e "\033[1;36m[+]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }
die()  { echo -e "\033[1;31m[x]\033[0m $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

# Resolve script location for optional follow-up actions.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- Config
RUST_TOOLCHAIN_DEFAULT="${RUST_TOOLCHAIN_DEFAULT:-stable}"
# If your build scripts hard-pin 1.71.1, keep it. Otherwise use stable.
RUST_TOOLCHAIN_PIN="${RUST_TOOLCHAIN_PIN:-1.71.1}"

# Rust targets we want
RUST_TARGET_LINUX_AARCH64="aarch64-unknown-linux-gnu"
RUST_TARGET_WIN64_GNU="x86_64-pc-windows-gnu"

# Where to write Cargo linker config (repo local)
WRITE_CARGO_CONFIG="${WRITE_CARGO_CONFIG:-1}"  # set to 0 to disable

main() {
  log "Updating apt metadata..."
  sudo apt-get update -y

  log "Installing base build dependencies..."
  sudo apt-get install -y \
    build-essential \
    pkg-config \
    ca-certificates \
    curl \
    git \
    make \
    perl \
    cmake \
    ninja-build \
    file \
    unzip \
    xz-utils \
    rsync \
    jq

  log "Installing cross toolchains..."
  # aarch64-linux-gnu cross compiler
  sudo apt-get install -y \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    binutils-aarch64-linux-gnu

  # Windows cross compiler (mingw-w64)
  sudo apt-get install -y \
    mingw-w64

  # Optional: armhf if you ever need it (your script says it's not supported)
  # sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils-arm-linux-gnueabihf

  # Helpful for debugging linkers/ELF
  log "Installing optional debugging helpers..."
  sudo apt-get install -y \
    llvm \
    lld \
    clang \
    patchelf || true

  # ---- Rust toolchain setup
  if ! command -v rustup >/dev/null 2>&1; then
    warn "rustup not found; installing rustup..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    # shellcheck disable=SC1090
    source "$HOME/.cargo/env"
  fi

  require_cmd rustup

  log "Installing Rust toolchains..."
  rustup toolchain install "$RUST_TOOLCHAIN_DEFAULT" -c rustfmt -c clippy || true
  # Many legacy build scripts pin 1.71.1; install it so they don't auto-download mid-build
  rustup toolchain install "$RUST_TOOLCHAIN_PIN" -c rustfmt -c clippy || true

  log "Adding Rust targets..."
  rustup target add "$RUST_TARGET_LINUX_AARCH64" --toolchain "$RUST_TOOLCHAIN_DEFAULT" || true
  rustup target add "$RUST_TARGET_WIN64_GNU"    --toolchain "$RUST_TOOLCHAIN_DEFAULT" || true

  # If your build script explicitly uses 1.71.1, ensure targets exist there too:
  rustup target add "$RUST_TARGET_LINUX_AARCH64" --toolchain "$RUST_TOOLCHAIN_PIN" || true
  rustup target add "$RUST_TARGET_WIN64_GNU"    --toolchain "$RUST_TOOLCHAIN_PIN" || true

  log "Rust toolchains installed:"
  rustup show

  # ---- Verify toolchains exist
  log "Verifying cross compiler commands..."
  require_cmd aarch64-linux-gnu-gcc
  require_cmd aarch64-linux-gnu-ar
  require_cmd x86_64-w64-mingw32-gcc
  require_cmd x86_64-w64-mingw32-gcc-ar

  # ---- Repo-local cargo config for linkers
  if [[ "$WRITE_CARGO_CONFIG" == "1" ]]; then
    log "Writing .cargo/config.toml in current directory (repo root)..."
    mkdir -p .cargo
    cat > .cargo/config.toml <<'EOF'
# Auto-generated by cross toolchain setup script.
# Ensures Rust uses the right cross linkers on Linux.

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
EOF

    log "Wrote .cargo/config.toml:"
    sed -n '1,200p' .cargo/config.toml
  else
    warn "WRITE_CARGO_CONFIG=0; skipping .cargo/config.toml creation."
  fi

  log "Done. Next steps:"
  cat <<'NEXT'
- Run your OpenSSL build + cargo cross builds (or your repo build script).
- Confirm outputs exist:
    target/x86_64-unknown-linux-gnu/release/*.so
    target/aarch64-unknown-linux-gnu/release/*.so
    target/x86_64-pc-windows-gnu/release/*.dll
- Then bundle/rename outputs into QDN publish directory.
NEXT

  read -r -p "Run the build script now to cross-compile binaries? [y/N] " RUN_BUILD
  if [[ "${RUN_BUILD}" == "y" || "${RUN_BUILD}" == "Y" ]]; then
    "${SCRIPT_DIR}/build.sh"
  fi
}

main "$@"
